runtime: python27
threadsafe: yes
api_version: 1

handlers:
- url: /css
  static_dir: styles
- url: /js
  static_dir: scripts
- url: /
  script: main.app
- url: .*
  script: main.app
  http_headers:
    Access-Control-Allow-Origin: "*"

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
- name: PIL
  version: "1.1.7"
- name: webob
  version: "1.2.3"